In [2]:
import numpy as np 

In [14]:
n = 20
r = 4 
t = (n - r) // r 
mask = np.arange(t+1) * r 
seq = np.random.randint(0, 100, 20) 
mask 

array([ 0,  4,  8, 12, 16])

In [16]:
mask + r - 1

array([ 3,  7, 11, 15, 19])

In [20]:
s = seq[mask + r - 1]
s 

array([76, 71, 94, 82, 71])

In [18]:
seq[-1]

71